### PR TITLE
Updated to graphql-java 3.0.0

### PR DESCRIPTION
**Pull request by ieugen**
* bumped project version to 3.0.0-SNAPSHOT
* did not test the code yet, just version update
* old generated code works after the version upgrade
* old code runs slower with version 3.0.0

### CODE REVIEW

**Comment by jmgrozas** [comment]
What is the problem in this pull request? I need this feature ... 

Thanks !!!

**Comment by brimworks** [comment]
Sorry, oversight on my part.... looking at it now.

**Comment by brimworks** [comment]
Released as version 3.0.0, it might take an hour or so to get to maven central.

Thanks,
-Brian

**Comment by jmgrozas** [comment]
thank you very much !!!!

**Pull request merged**
